---
version: '3.8'

services:
  frontend:
    image: robertdocan/pixelpals-frontend:v1.0
    ports:
      - "8081:3000"
    networks:
      - pixelpals_network
    restart: always

  backend:
    image: robertdocan/pixelpals-backend:v1.0
    ports:
      - "8080:8080"
    networks:
      - pixelpals_network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

networks:
  pixelpals_network:
    driver: bridge
