---
version: '3.8'
services:
  frontend:
    image: robertdocan/pixelpals-frontend:v1.0
    ports:
      - "8081:3000"  # Expose frontend on port 8081
    networks:
      - pixelpals_network
    restart: always  # Ensure frontend always restarts if stopped

  backend:
    image: robertdocan/pixelpals-backend:v1.0
    ports:
      - "8080:8080"  # Expose backend on port 8080
    networks:
      - pixelpals_network
    restart: always  # Ensure backend always restarts if stopped

networks:
  pixelpals_network:
    driver: bridge
