---
version: '3.8'
services:
  frontend:
    image: robertdocan/pixelpals-frontend:v1.0
    ports:
      - "8081:3000"
    networks:
      - pixelpals_network
  backend:
    image: robertdocan/pixelpals-backend:v1.0
    ports:
      - "8080:8080"
    restart: always
    networks:
      - pixelpals_network
networks:
  pixelpals_network:
    driver: bridge
