apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixelpals-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pixelpals-backend
  template:
    metadata:
      labels:
        app: pixelpals-backend
    spec:
      imagePullSecrets:
        - name: my-docker-secret  # Reference to your created secret
      containers:
        - name: go-backend
          image: robertdocan/pixelpals-backend:${{ github.sha }}  # Replace with your image
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pixelpals-backend-service
spec:
  selector:
    app: pixelpals-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
