name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # Backend job
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.0'

      - name: Build Go app
        run: |
          cd backend
          go mod tidy
          go build -o app main.go

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image for Go app
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pixelpals-backend:v1.0 .

      - name: Push Docker image for Go app
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/pixelpals-backend:v1.0

      - name: Deploy Go app to Ubuntu server
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} hevix@192.168.1.133 << EOF
            docker pull ${{ secrets.DOCKER_USERNAME }}/pixelpals-backend:v1.0 &&
            docker stop pixelpals-backend || true &&
            docker rm pixelpals-backend || true &&
            docker run -d --name pixelpals-backend -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/pixelpals-backend:v1.0
          EOF

  # Frontend job
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build React app
        run: |
          cd frontend
          npm install
          npm run build

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image for Frontend
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pixelpals-frontend:v1.0 .

      - name: Push Docker image for Frontend
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/pixelpals-frontend:v1.0

      - name: Deploy Frontend to Ubuntu server
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} hevix@192.168.1.133 << EOF
            docker pull ${{ secrets.DOCKER_USERNAME }}/pixelpals-frontend:v1.0 &&
            docker stop pixelpals-frontend || true &&
            docker rm pixelpals-frontend || true &&
            docker run -d --name pixelpals-frontend -p 80:80 ${{ secrets.DOCKER_USERNAME }}/pixelpals-frontend:v1.0
          EOF
