name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pixelpals:v1.0 .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/pixelpals:v1.0

      - name: Deploy Go app to Ubuntu server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem hevix@192.168.1.133 << EOF
            docker pull ${{ secrets.DOCKER_USERNAME }}/pixelpals-backend:v1.0 &&
            docker stop pixelpals-backend || true &&
            docker rm pixelpals-backend || true &&
            docker run -d --name pixelpals-backend -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/pixelpals-backend:v1.0
          EOF
