name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/pixelpals:v1.0 .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/pixelpals:v1.0

      - name: Deploy to Ubuntu server
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} user@<YOUR_UBUNTU_SERVER_IP> << EOF
            docker pull ${{ secrets.DOCKER_USERNAME }}/pixelpals:v1.0 &&
            docker stop pixelpals || true &&
            docker rm pixelpals || true &&
            docker run -d --name pixelpals -p 8080:8080 -p 80:80 ${{ secrets.DOCKER_USERNAME }}/pixelpals:v1.0
          EOF
